"""empty message

Revision ID: 200761d3b10a
Revises: 
Create Date: 2020-05-01 01:05:21.376449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '200761d3b10a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'restaurant_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('restaurant_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
