"""empty message

Revision ID: 39659ea1c7f5
Revises: fbdf1dd8f06a
Create Date: 2020-05-01 00:32:11.455408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39659ea1c7f5'
down_revision = 'fbdf1dd8f06a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
