"""empty message

Revision ID: 5bd5ca6793ca
Revises: 
Create Date: 2020-05-01 00:09:53.849060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bd5ca6793ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
