"""empty message

Revision ID: 92b265ccde53
Revises: 200761d3b10a
Create Date: 2020-05-01 01:06:08.021001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92b265ccde53'
down_revision = '200761d3b10a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'restaurant_id')
    # ### end Alembic commands ###
