"""empty message

Revision ID: e52888429b16
Revises: e4eb7ff1304d
Create Date: 2020-05-04 17:33:54.793085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e52888429b16'
down_revision = 'e4eb7ff1304d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurants', 'owner_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurants', 'owner_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
